# Generated by Django 3.2.13 on 2022-12-13 05:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_domain', models.CharField(max_length=200)),
                ('cpanel_domain', models.CharField(max_length=200)),
                ('created_by', models.CharField(max_length=200)),
                ('createdAt', models.DateTimeField(default=datetime.datetime(2022, 12, 13, 12, 31, 15, 22548))),
            ],
            options={
                'db_table': 'domain_group',
            },
        ),
    ]
